# we need super user level permissions
sudo: required
# we need docker installed (travis knows how to do this with just the name)
services:
  - docker

before_install:
  - docker build -t jakoblyon/temporal-boon-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jakoblyon/temporal-boon-test npm run test -- --coverage

after_success: 
  # Setup production images
  - docker build -t jakoblyon/temporal-boon-client ./client
  - docker build -t jakoblyon/temporal-boon-server ./server
  - docker build -t jakoblyon/temporal-boon-nginx ./nginx
  # Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push production images to Docker Hub
  - docker push jakoblyon/temporal-boon-client
  - docker push jakoblyon/temporal-boon-server
  - docker push jakoblyon/temporal-boon-nginx
  
# travis ci is preconfigured to know what elasticbeanstalk means
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  # app name in AWS
  app: "temporal-boon"
  env: "TemporalBoon-env"
  # aws -> services -> s3 -> my bucket
  bucket_name: "elasticbeanstalk-us-east-2-017242711305"
  # by default same name as app name
  bucket_path: "temporal-boon"
  # any time code is pushed to branched master, trigger deploy
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"