version: '3'
services:
  postgres:
    build:
      dockerfile: Dockerfile.dev
      context: ./db
    environment:
      - POSTGRES_DB=temp_boon_pg
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3000:80"
  api:
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - PGUSER=temp_boon_pg
      - PGHOST=postgres
      - PGDATABASE=temp_boon_pg
      - PGPASSWORD=postgres
      - PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  test:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    command: ["npm", "run", "test"]