export const types = {
  SET_BOSS: "SET_BOSS",
  ADD_ACTIVE_HEALER: "ADD_ACTIVE_HEALER",
  CHANGE_ACTIVE_HEALER: "CHANGE_ACTIVE_HEALER",
  ADD_TIMELINE_ROW: "ADD_TIMELINE_ROW",
  UPDATE_TIMELINE_BOSS_SPELL: "UPDATE_TIMELINE_BOSS_SPELL",
  UPDATE_TIMING: "UPDATE_TIMING",
  UPDATE_NOTES: "UPDATE_NOTES",
  ADD_HEALER_SPELL: "ADD_HEALER_SPELL",
  LOG_IN: "LOG_IN",
  LOG_OUT: "LOG_OUT"
}